- org:  Allied Testing
  role: Financial math trainings
  location: Moscow, RUS
  when: Nov 2007 - Mar 2008

- org:  Allied Testing
  role: Project Management trainings (Allied Testing)
  location: Moscow, RUS
  when: Apr 2008 - Sep 2008

- org:  Online Berkeley course    https://class.coursera.org/saas
  role: Software as a service (SAAS)
  location: Online
  when: Jan 2012 - Apr 2012

- org:  Online Stanford course  https://www.coursera.org/course/compilers
  role: Compilers.
  location: Online
  when: Oct 2012 - Dec 2012

- org:  Online Stanford course  https://class.coursera.org/gametheory-2012-002/class
  role: Game theory.
  location: Online
  when: Jan 2013 - Feb 2013

- org: Online Prineston course  https://class.coursera.org/algs4partI-002/class
  role: Algorithms
  location: Online
  when: Feb 2013 - Mar 2013

- org: Online Prineston course   https://class.coursera.org/algs4partII-001/class/index
  role: Algorithms part 2
  location: Online
  when: Apr 2013 - May 2013

- org: Axensis Moscow
  role: English courses (Upper Intermediate)
  location: Moscow, RUS
  when: Sep 2004 – May 2005

- org: Goethe institute, Moscow
  role: German courses (Intermediate)
  location: Moscow, RUS
  when: Sep 2005 – Sep 2007

- org: Avira
  role: German courses
  location: Tettnang, DE
  when: Sep 2013 - March 2014

- org: Cervantes institute, Moscow
  role: Spanish courses
  location: Moscow, RUS
  when: Jan 2010 - Jan 2011


- org: Private courses, Moscow
  role: Arabic courses
  location: Moscow, RUS
  when: Jan 2012 - Jun 2012

